require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# use_frameworks!

target 'ReactNativeSemaphoreNew' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  target 'ReactNativeSemaphoreNewTests' do
    inherit! :complete
    # Pods for testing
  end

  # pre_install do |installer|
  #   codegen_pre_install(installer)
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # 
  # use_flipper!
  # post_install do |installer|
  #  flipper_post_install(installer)
  # end

  # Fixes: https://github.com/facebook/react-native/issues/31034#issuecomment-812564390
  # post_install do |installer|
  #   react_native_post_install(installer)
    
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  #     end
      
  #     if (target.name&.eql?('FBReactNativeSpec'))
  #       target.build_phases.each do |build_phase|
  #         if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
  #           target.build_phases.move(build_phase, 0)
  #         end
  #       end
  #     end
  #   end
  # end
end